### ISSUE TITLE
Error in setup.cfg: command 'install_data' has no such option 'post_hook.fix_alignak_cfg'

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#1009] opened 2018-03-28 10:25 UTC
On a fresh install on develop, installation seems broken in hooks of `setup.cfg`:

```python
    running install_data
    error: error in setup.cfg: command 'install_data' has no such option 'post_hook.fix_alignak_cfg'
error
Cleaning up...
  Removing source in /tmp/pip-WPVuHn-build
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-WPVuHn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-EvR3tu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-WPVuHn-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-WPVuHn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-EvR3tu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-WPVuHn-build/
```

When checkout to recent tag (`v1.1.b`), installation seems work.

**pip freeze**
```python
CherryPy==8.9.1
docopt==0.6.2
importlib==1.0.4
numpy==1.14.2
psutil==5.4.3
requests==2.14.2
setproctitle==1.1.10
six==1.11.0
termcolor==1.1.0
ujson==1.35
```

**Tested pip versions:** `9.0.2` and `9.0.3`
**OS:** Ubuntu Server 16.04.4 LTS (Xenial)

**Comment by ls-initiatives** [comment] 2018-06-19 14:36
Any progress ?

**Comment by mohierf** [comment] 2018-06-20 18:19
@ls-initiatives : sorry for the late being on this problem but I focused on the very soon new release.

I informed algorys that the problem is because of the missing `pbr` requirement but I did not updated the issue. I just gave a try with the most recent develop branch and I installed successfuly. Would you mind make a confirmation please ?

**Comment by ls-initiatives** [comment] 2018-06-20 21:41
Thanks for the update, I totally understand you focus on the release.
I doubt I can spend the time to pull/test the dev branch, sorry.
I tried the latest RC in pip but I can try again on the next RC if you want.

**Comment by mohierf** [comment] 2018-06-21 07:50
Thanks. The latests PIP rc is 1.1.0rc5 and I am currently testing this on several Linux/FreeBSD to fine tune the delivery ...

I just updated the installation doc here: http://docs.alignak.net/en/develop-environment/02_installation/index.html and I am still improving this part of the documentation to make it as clear and documented as possible.

Do not hesitate to ask for more information if needed: IRC #alignak

**Comment by mohierf** [comment] 2018-07-22 11:55
Fixed in python3 branch

**Closed by mohierf** 2018-07-22 11:55 UTC
